# Generated by Django 4.1.1 on 2022-09-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='empresa',
            field=models.CharField(default='Sem empresa', max_length=50),
        ),
    ]
